# travis config
sudo: required
services:
  - docker

before_install:
  - docker build -t andnig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andnig/docker-react npm run test -- --coverage