# travis config
sudo: required
services:
  - docker
language: generic
before_install:
  - docker build -t andnig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andnig/docker-react npm run test -- --coverage

# deploy this container to AWS elasticbeanstalk (great way to launch single container apps)
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Sample Application"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk--us-east-2-550996401687"
  bucket_path: "docker-react"
  on:
    branch: master
# these are env. variables in travis CI
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"